
CREATE WAREHOUSE DEMO_WH WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;


USE WAREHOUSE DEMO_WH;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER LIMIT 10;

CREATE DATABASE DEMO_DB;
